
server:
  port: 8861
dubbo:

  # 配置服务信息
  application:
    name: server-provider
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:

    address: nacos://150.158.172.61:8848
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: 20880

spring:
  main:
    # 解决Bean重复定义问题
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/server-demo?setUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 930726zs


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
